OrderManagementApp/Models/Orders.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderManagementApp.Models
{
    public class Orders
    {
        [Key] 
        public int Id { get; set; }
        public DateTime OrderDate { get; set; } = DateTime.Now;
        public double TotalAmount { get; set; }
        public string? CustomerName { get { return ApplicationUser.UserName; } }

        //Navigation property order -> user r/n
        public string? ApplicationUserId { get; set; }
        [ForeignKey("ApplicationUserId")]
        public virtual ApplicationUser? ApplicationUser { get; set; }
        

        //OrdersDetail navigation property order -> OrdersDetails many to one
        public virtual List<OrdersDetail> OrdersDetails { get; set; } = new List<OrdersDetail>();
    }

}

OrderManagementApp/Models/OrdersDetail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderManagementApp.Models
{
    public class OrdersDetail
    {
        [Key]
        public int Id { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; } 
        public double SubTotal { get; set; }/*{ get { return Quantity * UnitPrice; } }*/
        public double VAT { get; set; } = 0.15;
        public double TaxAmount { get; set; }
        public double Total { get; set; }
        public DateTime OrderDate { get; set; }
       
        //navigation property
        /*public int OrderId { get; set; }
        [ForeignKey("OrderId")]
        public virtual Orders Order { get; set; }*/

        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public virtual Product? Product { get; set; }
        public string? ApplicationUserId { get; set; }
        [ForeignKey("ApplicationUserId")]
        public virtual ApplicationUser? ApplicationUser { get; set; }

    }
}

OrderManagementApp/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderManagementApp.Data;
using OrderManagementApp.Models;
using System.Security.Claims;

namespace OrderManagementApp.Controllers
{
  
    public class OrdersController : Controller
    {
        private readonly OrderDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public OrdersController(OrderDbContext context, UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

       public async Task<IActionResult> Index()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            List<Orders> orders = await context.Orderz
               .Include(x => x.OrdersDetails)
               .Include(x => x.ApplicationUser)
               .ToListAsync();

            Orders order = context.Orderz
                .Include(x => x.OrdersDetails)
                .Include(x => x.ApplicationUser)
                .FirstOrDefault();
            return View(order);
        }

        public async Task<IActionResult> Add()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            List<OrdersDetail> ordersDetail = await context.OrdersDetailz
                .Include(x => x.Product)
                .ToListAsync();

            Orders order = new Orders();
           
            order.OrderDate = DateTime.Now;
            order.ApplicationUser = user;
            order.ApplicationUserId = user.Id;


            foreach (var item in ordersDetail)
            {
                //order.OrdersDetails.Add(item);
                order.TotalAmount += item.Total;
            }
            context.Orderz.Add(order);
            await context.SaveChangesAsync();
           
            return RedirectToAction("Index");
        }
        

        /*public async Task<IActionResult> RemoveAll()
        {
            List<OrdersDetail> ods = await context.OrdersDetailz.ToListAsync();

            context.OrdersDetailz.RemoveRange(ods);
            context.SaveChanges();
            return RedirectToAction("Index");
        }*/
    }
   
}

OrderManagementApp/Controllers/OrdersDetailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderManagementApp.Data;
using OrderManagementApp.Models;
using OrderManagementApp.ViewModels;
using System.Security.Claims;

namespace OrderManagementApp.Controllers
{
    public class OrdersDetailController : Controller
    {
        private readonly OrderDbContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public OrdersDetailController(OrderDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }


        public async  Task<IActionResult> Index()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);
            List<OrdersDetail> orderDetails = context.OrdersDetailz
                .Include(x => x.ApplicationUser)
                .Include(x => x.Product)
                .Where(x => x.ApplicationUser.Id == user.Id)
                .ToList();
            return View(orderDetails);
            
        }
        public async Task<IActionResult> Add(int id)
        {
            ApplicationUser user = await userManager.GetUserAsync(User);
            //Get the ordered product
            var product = await context.productz.FirstOrDefaultAsync(x => x.Id == id);

            var orderDetails = await context.OrdersDetailz
                .Include(x => x.ApplicationUser)
                .Include(x => x.Product)
                .Where(x => x.ProductId == product.Id)
                .Where(x => x.ApplicationUser.Id == user.Id)
                .FirstOrDefaultAsync();
            
            OrdersDetail od = new OrdersDetail();
            
            if (orderDetails == null)
            {
                od.ProductId = product.Id;
                od.UnitPrice = product.Price;
                od.Quantity = 1;
                od.OrderDate = DateTime.Now;
                od.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                od.SubTotal = od.UnitPrice * od.Quantity;
                od.TaxAmount = (od.VAT * od.SubTotal);
                od.Total = od.TaxAmount + od.SubTotal;
                context.OrdersDetailz.Add(od);
                await context.SaveChangesAsync();
            }
            else
            {
                od = orderDetails;
                od.Quantity += 1;
                od.OrderDate = DateTime.Now;
                od.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                od.SubTotal = od.UnitPrice * od.Quantity;
                od.TaxAmount = (od.VAT * od.SubTotal);
                od.Total = od.TaxAmount + od.SubTotal;
                context.Update(od);
                context.SaveChanges();
            }

            
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Decrease(int id)
        {
            ApplicationUser user = await userManager.GetUserAsync(User);

            var od = await context.OrdersDetailz
                .Include(x => x.Product)
                .Include(x => x.ApplicationUser)
                .Where(x => x.Id == id)
                .Where(x => x.ApplicationUser.Id == user.Id)
                .FirstOrDefaultAsync();
           
            if (od.Quantity > 1)
            {
                --od.Quantity;
                od.SubTotal = od.UnitPrice * od.Quantity;
                od.TaxAmount = (od.VAT * od.SubTotal);
                od.Total = od.TaxAmount + od.SubTotal;
                context.OrdersDetailz.Update(od);
               
            }
            else
            {
                context.OrdersDetailz.Remove(od);
                
            }
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveAll()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);
            List<OrdersDetail> ods = await context.OrdersDetailz
                .Include(x => x.ApplicationUser)
                .Include(x => x.Product)
                .Where(x => x.ApplicationUser.Id == user.Id)
                .ToListAsync();
           
            context.OrdersDetailz.RemoveRange(ods);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Orders()
        {
            List<OrdersDetail> orderDetails = await context.OrdersDetailz
                .Include(x => x.Product)
                .Include(x => x.ApplicationUser)
                .ToListAsync();
            return View(orderDetails);
        }
    }
}

OrderManagementApp/Views/OrdersDetail/Index.cshtml
@model IEnumerable<OrdersDetail>

@{
    double grandTotal = 0;
  
}

    @if (@Model.Any())
{
    <h2 class="text-center text-bg-success mt-2">Your Orders</h2>
    <table class="table">
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>SubTotal</th>
            <th>VAT</th>
            <th>Tax Amout</th>
            <th>Total</th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
               
                <td><img src="~/img/@item.Product.Image" class="img-fluid" alt="image" width="150"/><br />@item.Product.ProductName</td>
                <td>@item.UnitPrice.ToString("C")</td>
                <td>@item.Quantity</td>
                <td>@item.SubTotal.ToString("C")</td>
                <td>@item.VAT</td>
                <td>@item.TaxAmount.ToString("C2")</td>
                <td>@item.Total.ToString("C2")</td>
                <td><a asp-action="Add" asp-route-id="@item.ProductId" class="btn btn-sm btn-success">+</a></td>
                <td><a asp-action="Decrease" asp-route-id="@item.Id" class="btn btn-sm btn-warning">-</a></td>
            </tr>
            grandTotal += @item.Total;
        }


    </table>
    <h6 >Grand Total: @grandTotal.ToString("C2")</h6>


@*<a class="btn btn-primary" asp-controller="Orders" asp-action="Add">Purchase</a>
*@<a class="btn btn-primary" asp-controller="" asp-action="Index">Back</a>
<a class="btn btn-danger" asp-action="RemoveAll">Remove Orders</a>
}
else{
    <h2 class="text-center text-bg-info mt-5">Your Cart Is Empty ☹️</h2>
    <a class="btn btn-info text-center" asp-controller="Product" asp-action="Index">Go To Products</a>
}



 

OrderManagementApp/Views/OrdersDetail/Orders.cshtml
@model IEnumerable<OrdersDetail>
@inject SignInManager<ApplicationUser> signInManager

@{
    double grandTotal = 0;
  
}
@if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    @if (@Model.Any())
{
    <h2 class="text-center text-bg-success mt-2">Orders</h2>
    <table class="table">
        <tr>
            <th>Customer Name</th>
            <th>Phone Number</th>
            <th>City</th>
            <th>Date</th>
            <th>Product</th>
            <th>Product Id</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>SubTotal</th>
            <th>VAT</th>
            <th>Tax Amout</th>
            <th>Total</th>
           
        </tr>

        @foreach (var item in Model)
        {
            <tr>
               
                <td>@item.ApplicationUser.UserName</td>
                <td>@item.ApplicationUser.PhoneNumber</td>
                <td>@item.ApplicationUser.City</td>
                <td>@item.OrderDate</td>
                <td>@item.Product.ProductName</td>
                <td>@item.ProductId</td>
                
                <td>@item.UnitPrice.ToString("C")</td>
                <td>@item.Quantity</td>
                <td>@item.SubTotal.ToString("C")</td>
                <td>@item.VAT</td>
                <td>@item.TaxAmount.ToString("C2")</td>
                <td>@item.Total.ToString("C2")</td>
       
            </tr>
            grandTotal += @item.Total;
        }


    </table>
    @*<h6 >Grand Total: @grandTotal.ToString("C2")</h6>*@



<a class="btn btn-primary" asp-controller="" asp-action="Index">Back</a>
<a class="btn btn-danger" asp-action="RemoveAll">Remove Orders</a>
}
else{
    <h2 class="text-center text-bg-info mt-5">Empty Order</h2>
   
}

}

 